source 'https://rubygems.org'
gem 'nokogiri'
gem 'rest-client'#, '~>1.1'
gem 'thor'#, :require => 'spec'
gem 'tree'
gem 'mechanize'
gem 'twitter', '~>5.14'
gem 'tweetstream'
gem 'json'
gem 'twitter_ebooks'